  # This is a basic workflow to help you get started with Actions

name: Multi Versions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "demo-ci" ]
  pull_request:
    branches: [ "demo-ci" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    exemple_multi_version:
        name: ‚ö°Ô∏è Use many os & node versions
        strategy:
          # continuer √† excuter les autres workflow si un √©choue !!! :)
          fail-fast: false 
          matrix:
            os: [windows-latest, ubuntu-latest]
            node: [12, 14, 16]
            include:
              - os: windows-latest
                node: 16
                npm: 6

        runs-on: ${{ matrix.os }}
        steps:
          - name: ‚öôÔ∏è Setup node
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node }}
        
          - name: üîß only install on windows npm 6
            if: ${{ matrix.npm }}
            run: npm install -g npm@${{ matrix.npm }}

          - name: üëÄ Read npm version 
            run: npm --version

          - name: üîñ Read node version 
            run: node --v