# This is a basic workflow to help you get started with Actions

name: conditions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "demo-ci" ]
  pull_request:
    branches:  [ "demo-ci" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
      name: ðŸš€ Deploy
      runs-on: ubuntu-latest
      steps:
        - name: ðŸš€ Deploy Staging
          if: ${{ github.ref == 'refs/heads/demo-ci' }}
          run: echo deploying in staging !

        - name: ðŸš€ Deploy Production
          if: ${{ github.ref == 'refs/heads/main' }}
          run: echo deploying in Production !


